require "paq" {
  {
    "ThePrimeagen/refactoring.nvim",
    requires = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-treesitter/nvim-treesitter" },
    },
  },
  {
    "numToStr/Comment.nvim",
    config = function()
      require("Comment").setup()
    end,
  },
  "davidsierradz/cmp-conventionalcommits",
  "JohnnyMorganz/StyLua",
  "Olical/conjure",
  "ThePrimeagen/harpoon",
  "clojure-vim/vim-jack-in",
  "glepnir/dashboard-nvim",
  "gruvbox-community/gruvbox",
  "neovim/nvim-lspconfig",
  "hrsh7th/cmp-buffer",
  "L3MON4D3/LuaSnip",
  "saadparwaiz1/cmp_luasnip",
  "SirVer/ultisnips",
  "dcampos/nvim-snippy",
  "dcampos/cmp-snippy",
  "quangnguyen30192/cmp-nvim-ultisnips",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-vsnip",
  "hrsh7th/cmp-vsnip",
  "hrsh7th/nvim-cmp",
  "hrsh7th/nvim-cmp",
  "hrsh7th/vim-vsnip",
  "hrsh7th/vim-vsnip",
  "kyazdani42/nvim-web-devicons",
  "lewis6991/gitsigns.nvim",
  "mfussenegger/nvim-dap",
  "neovim/nvim-lspconfig",
  "nvim-lua/plenary.nvim",
  "hrsh7th/cmp-nvim-lua",
  "nvim-telescope/telescope.nvim",
  "nvim-treesitter/nvim-treesitter",
  "radenling/vim-dispatch-neovim",
  "savq/paq-nvim",
  "tmux-plugins/vim-tmux",
  "tpope/vim-dispatch",
  "tpope/vim-fugitive",
  "vimwiki/vimwiki",
  "wesleimp/stylua.nvim",
  {
    "kaicataldo/material.vim",
    branch = "main",
  },
  {
    "kyazdani42/nvim-tree.lua",
    requires = "kyazdani42/nvim-web-devicons",
    config = function()
      require("nvim-tree").setup {}
    end,
  },
  {
    "nvim-lualine/lualine.nvim",
    requires = { "kyazdani42/nvim-web-devicons", opt = true },
  },
}
